name: Firebase

on:
  push:
    branches: [main]

jobs:
  hosting:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: ./package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Install Ionic CLI
        run: npm i --save @ionic/cli

      - name: Build Ionic application
        run: ionic build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_HOSTING_KEY }}
          channelId: dev
