name: Heroku

on:
  push:
    branches: [main]

jobs:
  react:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: 'empatduapuluh'
          heroku_email: 'dzulfiqar@student.umn.ac.id'
